### ISSUE TITLE
Sync with new API change

### ISSUE THREAD

**Issue by shaokeyibb** [Toktik-Team/toktik#29]
In douyin_message_chat_request:
- [x] pre_msg_time

In Message message:
- [x] create_time

In User:
- avatar
  - [x] database
  - [x] service impl (gravatar/cravatar)
- background_image
  - [x] database
  - [x] service impl
- signature
  - [x] database
  - [x] service impl
- total_favorited
  - [x] database
  - [x] service impl
- work_count
  - [x] database
  - [x] service impl
- favorite_count
  - [x] database
  - [x] service impl

**Comment by nicognaW** [comment]
Avatar is done perfectly with explicit logic by https://github.com/Toktik-Team/toktik/commit/458070ba12744b3144152b0886715e3c7d891fa0.

Background image is using Unsplash api and cravatar as fallback.

Need some cool idea for signature, I will experiment with OpenAI API later this day.

Message stuff should be ready as well by the end of this day.

**Comment by shaokeyibb** [comment]
What about [hitokoto API](https://developer.hitokoto.cn/)?

**Comment by nicognaW** [comment]
> What about [hitokoto API](https://developer.hitokoto.cn/)?

Noticed

**Comment by nicognaW** [comment]
Closing this issue, and leaving the signature feature as an further optimization
